complete -c mdcat -n __fish_use_subcommand -l columns -d 'Maximum number of columns to use for output'
complete -c mdcat -n __fish_use_subcommand -s p -l paginate -d 'Paginate the output of mdcat with a pager like less.'
complete -c mdcat -n __fish_use_subcommand -s P -l no-pager -d 'Do not page output.  Default if invoked as mdcat'
complete -c mdcat -n __fish_use_subcommand -s c -l no-colour -d 'Disable all colours and other styles.'
complete -c mdcat -n __fish_use_subcommand -s l -l local -d 'Do not load remote resources like images'
complete -c mdcat -n __fish_use_subcommand -l dump-events -d 'Dump Markdown parser events and exit'
complete -c mdcat -n __fish_use_subcommand -l fail -d 'Exit immediately if any error occurs processing an input file'
complete -c mdcat -n __fish_use_subcommand -l detect-only -d 'Only detect the terminal type and exit'
complete -c mdcat -n __fish_use_subcommand -l ansi-only -d 'Limit to standard ANSI formatting'
complete -c mdcat -n __fish_use_subcommand -s h -l help -d 'Prints help information'
complete -c mdcat -n __fish_use_subcommand -s V -l version -d 'Prints version information'
